/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pantallas;

/**
 *
 * @author piero
 */
public class FrameRegistrar extends javax.swing.JFrame {

    /**
     * Creates new form Frameingresar
     */
    public FrameRegistrar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        lbl = new javax.swing.JLabel();
        lblimagen = new javax.swing.JLabel();
        lblnombre = new javax.swing.JLabel();
        lblapellidos = new javax.swing.JLabel();
        lblusuario = new javax.swing.JLabel();
        lbldni = new javax.swing.JLabel();
        lblcorreo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Txtnombre = new javax.swing.JTextField();
        Txtapellidos = new javax.swing.JTextField();
        Txtusuario = new javax.swing.JTextField();
        Txtdni = new javax.swing.JTextField();
        Txtcorreo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btmRegistrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(155, 109, 54));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesFrameRegistrar/Rectangle 14.png"))); // NOI18N

        lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesFrameRegistrar/Ayudanos a encontrar mascostas.png"))); // NOI18N

        lblimagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesFrameRegistrar/Ellipse 2.png"))); // NOI18N

        lblnombre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesFrameRegistrar/Nombre_.png"))); // NOI18N

        lblapellidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesFrameRegistrar/Apellidos_.png"))); // NOI18N

        lblusuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesFrameRegistrar/Usuario_.png"))); // NOI18N

        lbldni.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesFrameRegistrar/DNI_.png"))); // NOI18N

        lblcorreo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesFrameRegistrar/Correo_.png"))); // NOI18N

        jPanel2.setBackground(new java.awt.Color(155, 109, 54));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Txtnombre.setBackground(new java.awt.Color(217, 217, 217));
        Txtnombre.setBorder(null);
        jPanel2.add(Txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 14, 150, -1));

        Txtapellidos.setBackground(new java.awt.Color(217, 217, 217));
        Txtapellidos.setBorder(null);
        jPanel2.add(Txtapellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 54, 150, -1));

        Txtusuario.setBackground(new java.awt.Color(217, 217, 217));
        Txtusuario.setBorder(null);
        jPanel2.add(Txtusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 94, 150, -1));

        Txtdni.setBackground(new java.awt.Color(217, 217, 217));
        Txtdni.setBorder(null);
        jPanel2.add(Txtdni, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 134, 150, -1));

        Txtcorreo.setBackground(new java.awt.Color(217, 217, 217));
        Txtcorreo.setBorder(null);
        jPanel2.add(Txtcorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 174, 150, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesFrameRegistrar/Rectangle 3 (1).png"))); // NOI18N
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesFrameRegistrar/Rectangle 3 (1).png"))); // NOI18N
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesFrameRegistrar/Rectangle 3 (1).png"))); // NOI18N
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesFrameRegistrar/Rectangle 3 (1).png"))); // NOI18N
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesFrameRegistrar/Rectangle 3 (1).png"))); // NOI18N
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesFrameRegistrar/Group 6.png"))); // NOI18N
        btnCancelar.setBorder(null);
        btnCancelar.setBorderPainted(false);
        btnCancelar.setContentAreaFilled(false);

        btmRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesFrameRegistrar/Group 7.png"))); // NOI18N
        btmRegistrar.setBorder(null);
        btmRegistrar.setBorderPainted(false);
        btmRegistrar.setContentAreaFilled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(logo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblnombre, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblapellidos, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblusuario, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbldni, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblcorreo, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(btnCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(btmRegistrar)
                .addGap(26, 26, 26))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl)
                        .addGap(70, 70, 70))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblimagen)
                        .addGap(97, 97, 97))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(logo)
                .addGap(39, 39, 39)
                .addComponent(lblimagen)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(lblnombre)
                        .addGap(29, 29, 29)
                        .addComponent(lblapellidos)
                        .addGap(29, 29, 29)
                        .addComponent(lblusuario)
                        .addGap(30, 30, 30)
                        .addComponent(lbldni)
                        .addGap(30, 30, 30)
                        .addComponent(lblcorreo))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btmRegistrar))
                .addGap(42, 42, 42)
                .addComponent(lbl)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameRegistrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameRegistrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameRegistrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameRegistrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameRegistrar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Txtapellidos;
    private javax.swing.JTextField Txtcorreo;
    private javax.swing.JTextField Txtdni;
    private javax.swing.JTextField Txtnombre;
    private javax.swing.JTextField Txtusuario;
    private javax.swing.JButton btmRegistrar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl;
    private javax.swing.JLabel lblapellidos;
    private javax.swing.JLabel lblcorreo;
    private javax.swing.JLabel lbldni;
    private javax.swing.JLabel lblimagen;
    private javax.swing.JLabel lblnombre;
    private javax.swing.JLabel lblusuario;
    private javax.swing.JLabel logo;
    // End of variables declaration//GEN-END:variables
}
